[package]
name = "rsdb-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsdb_rs = { path = "../rsdb-rs" }
clap = { version = "4.5.8", features = ["derive"] }
