[package]
name = "rsdb-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsdbrs = { path = "../rsdbrs" }
clap = { version = "4.5.8", features = ["derive"] }
rustyline = "14.0.0"
